# Generated by Django 5.2.8 on 2025-12-06 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_following_data(apps, schema_editor):
    """Copy data from 'following' to 'following_user'."""
    Follow = apps.get_model('project', 'Follow')
    for follow in Follow.objects.all():
        follow.following_user_id = follow.following_id
        follow.save()


def reverse_migrate_following_data(apps, schema_editor):
    """Copy data from 'following_user' back to 'following'."""
    Follow = apps.get_model('project', 'Follow')
    for follow in Follow.objects.filter(following_user__isnull=False):
        follow.following_id = follow.following_user_id
        follow.save()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        # Step 1: Remove old unique_together constraint
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        # Step 2: Add new columns (nullable, no constraints yet)
        migrations.AddField(
            model_name='follow',
            name='following_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='project.hackerhouse'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        # Step 3: Migrate data from 'following' to 'following_user'
        migrations.RunPython(migrate_following_data, reverse_migrate_following_data),
        # Step 4: Update follower field related_name
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
        # Step 5: Remove old 'following' field
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        # Step 6: Add constraints AFTER data is migrated and old field removed
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('following_house__isnull', True), ('following_user__isnull', False)), models.Q(('following_house__isnull', False), ('following_user__isnull', True)), _connector='OR'), name='follow_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('following_user__isnull', False)), fields=('follower', 'following_user'), name='unique_user_follow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(condition=models.Q(('following_house__isnull', False)), fields=('follower', 'following_house'), name='unique_house_follow'),
        ),
    ]
